from enum import Enum

class SCHWARTZ_VALUES(Enum):
    SELF_DIRECTION = 0  
    STIMULATION = 1 
    HEDONISM = 2
    ACHIEVEMENT = 3
    POWER = 4
    SECURITY = 5
    CONFORMITY = 6
    TRADITION = 7
    BENEVOLENCE = 8
    UNIVERSALISM = 9


class ROCKEACH_VALUES(Enum):
    CHEERFULNESS = 0
    AMBITION = 1
    LOVE = 2
    CLEANLINESS = 3
    SELF_CONTROL = 4
    CAPABILITY = 5
    COURAGE = 6
    POLITENES = 7
    HONESTY = 8
    WISDOM = 9
    SALVATION = 10
    FAMILY_SECURITY = 11
    NATIONAL_SECURITY = 12
    ACCOMPLISHMENT = 13
    WORLD_BEAUTY = 14
    WORLD_PEACE = 15
    COMFORTABILITY = 16
    EXCITEMENT = 17
